### ISSUE TITLE
Publish Addon on Divio Cloud

### ISSUE THREAD

**Issue by FinalAngel** [arteria/djangocms-inline-comment#1]
Hello @jvamvas it would be amazing if you could publish the Addon on the Divio Cloud:

http://support.divio.com/marketplace/addons/how-to-publish-addons-on-the-django-cms-marketplace

**Comment by jvamvas** [comment]
Addon is now available on https://marketplace.django-cms.org/en/addons/browse/djangocms-inline-comment/
